all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /Users/enzoaugie/.ssh/id_rsa_takima
    postgres_db: db
    postgres_user: usr
    postgres_password: pwd
  children:
    prod:
      hosts: enzo.augie.takima.school
