name: Deploy with Ansible

on:
  workflow_run:
    workflows: ["Deploy Docker Images"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_takima
          chmod 600 ~/.ssh/id_rsa_takima
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          # Vérifier que la clé est bien écrite
          wc -c ~/.ssh/id_rsa_takima

      - name: Run Ansible playbook
        run: ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml --private-key=~/.ssh/id_rsa_takima -u admin
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
