name: CI devops 2025
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Job 1 : Build et test du backend
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify --file ./TP1-Docker/backend/simpleapi/pom.xml

  # Job 2 : Analyse SonarCloud
  # Ne se lance que si test-backend est passé
  sonarcloud:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=EnzoAUGIE_DevOps -Dsonar.organization=enzoaugie -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./TP1-Docker/backend/simpleapi/pom.xml

  # Job 3 : Build et push de l'image backend
  # Ne se lance que si sonarcloud est passé ET uniquement sur main
  build-and-push-backend:
    needs: sonarcloud
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./TP1-Docker/backend/simpleapi
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
          push: true

  # Job 4 : Build et push de l'image database
  # Ne se lance que si sonarcloud est passé ET uniquement sur main
  build-and-push-database:
    needs: sonarcloud
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./TP1-Docker/database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true

  # Job 5 : Build et push de l'image httpd
  # Ne se lance que si sonarcloud est passé ET uniquement sur main
  build-and-push-httpd:
    needs: sonarcloud
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./TP1-Docker/httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true
